# Generated by Django 4.0.3 on 2022-04-20 10:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name', 'author'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='picture',
        ),
        migrations.AddField(
            model_name='book',
            name='country',
            field=models.CharField(default='Kazakhstan', max_length=30),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='kazakh', max_length=30),
        ),
        migrations.AddField(
            model_name='book',
            name='page_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='year_published',
            field=models.DateField(default=datetime.datetime(2022, 4, 20, 10, 22, 50, 43752, tzinfo=utc)),
        ),
    ]
